name: Android CI

on:
  push:
    branches:
      - expense_tracker_qa
      - main
      - app_test_case
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload HTML Report
        uses: actions/checkout@v4
        with:
          name: lint.html
          path: app/build/ports/lint-result.html

  build:
    name: Build Expense Tracker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Execute Permission To Gradle
        run: chmod +x gradlew

      - name: Build Apk
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
